[package]
name = "zstd"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
env_logger = "0.11.8"
log = { version = "0.4.27", features = ["release_max_level_off"] }
